### PR TITLE
Project structure changes

### PR DESCRIPTION
**Pull request by Hexer10**
This PR aims to update the current codebase do the new Custom Language project structure, introducing the following changes:

- [x] Migrate to gradle (Kotlin DSL).
- [x] Re-create plugin.xml.
- [x] Update directory structure to `src/main/<lang>/<package>`.
- [x] Generate the parser and the lexer to the same folder (currently they are generated in `src/main/gen` and `gen`). Generated code will be located in `src/main/gen`.
- [x] Migrate the project codebase to Kotlin. 
- [x] Grammar files moved to `src/main/grammar/`.

Currently the plugin runs successfully on IDEA 2020.3.1

### CODE REVIEW

**Comment by Hexer10** [comment]
I wanted to address a question about the code style:
Do you prefer using the shorthand for function with just  a return or do you prefer the full way?
Also I'm not sure on how to set the parser and lexer output path do you have any pointers?

**Comment by Hexer10** [comment]
Also I'm not sure if this was wanted but the project name is idea-sp but the Javaclass name is idea_sp

**Comment by theY4Kman** [comment]
re: code style: I don't recall the full semantics of Kotlin, but my opinion would be: for a one-expression function, omitting the `return` keyword is acceptable; if there is more than one statement, the `return` keyword is required.

re: project name: I have no strong opinions of the name, as long as it's clear it's related to SourcePawn and IDEA/Jetbrains IDE. If you've got a better name, I'm all ears.

FYI: I'm on vacation till tomorrow, so I don't think I'll be able to give the attention this PR needs, or merge it, till then.

Also, I'd love to see this thing come to fruition. I've also got a job, a new house, and a wife and kid vying for attention :P It seems wise to have more than just me as maintainer, to keep the spirit alive and the drive strong. And in general, I'd love a second pair of eyes to help keep the project on the right track. If you're interested, I can expand out that TODO issue into separate tickets, write some descriptions, some pointers, etc; we can talk about them, and do PR-based development.

**Comment by Hexer10** [comment]
Thanks for replying, I'd really love to contribute more to this project, I've also had some experience with the Intellij API, I just find hard how to integrate it with JFlex and Bnf.

I think the name `idea-sp` is fine, I'd just avoid having the project name `idea-sp` and the classname `idea_sp`.

EDIT: I guess the package name `idea_sp` is due to the fact that `idea-sp` is not a valid package name 

When you have time it would be nice to split up the todos so we can track better the tasks

**Comment by theY4Kman** [comment]
I just attempted to clone the repo and run the plugin, and as you probably encountered, it didn't work out of the box :P I pulled your branch, and things are running. I'm happy to merge this as-is, just so `master` is useful. We can fix the generated parser file locations afterward.

I'll add you as a maintainer, so at least you can push feature branches directly on the repo.

**Comment by Hexer10** [comment]
> I just attempted to clone the repo and run the plugin, and as you probably encountered, it didn't work out of the box :P I pulled your branch, and things are running. I'm happy to merge this as-is, just so `master` is useful. We can fix the generated parser file locations afterward.
> 
> I'll add you as a maintainer, so at least you can push feature branches directly on the repo.

Much thanks! Btw I just updated the kotlin dls so the generated files are all located in `src/gen` and I moved the grammar files to `src/grammar`

This now should be ready to be merged

**Review by theY4Kman — APPROVED** [review]
lgtm

Heads-up: there's a bunch of files without trailing newlines. I'd ask for them to be added, but I want this merged :P

**Pull request merged**
